### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by dapa5900** [OmarEmaraDev/shader-selector-nodes#1]
Hi @OmarEmaraDev,

thanks a lot for your work on this addon. I just downloaded and tested the initial version. Overall I think it already looks very good and it will certainly be a huge help for a lot of use cases. There are a couple of issues I would like to address though. Here's my feedback so far:

1. In general, this is my setup with AN to get an index based distribution working. Is this the correct approach to do this, or are there other more straightforward ways to do this?
 
![indexBasedDistribution](https://user-images.githubusercontent.com/75205162/125284687-1079ba80-e31a-11eb-8efd-f0f5cb1ee298.jpg)

2. The "Vector"-values doesn't seem to do anything in my case (moving the texture), neither in the node itself nor by using Texture Coordinates and Mapping Nodes as input.

3. It would be great if we can get a manual re-order-function for the textures (eg. with up-and-down arrows or better via drag and drop if possible).

4. Whenever I click any of the buttons with the exception of "Browse" all connections to the node get removed.

5. For the 2 random modes I think it would be great to implement a seed value to quickly switch between different distributions.

6. When clearing textures from the list with the "X"-button the assigned textures on the objects don't update. For me only clearing everything and doing a re-import currently works for updating.

7. When adding a texture via "Add" the texture won't get used. I can see that when batch adding them via "Browse" there are 2 users for the texture which is not the case when using the "Add" function. Maybe that's the source for this issue?

Think this is it for now. Thanks again and looking forward to the next version :)

P.S.: Please find here my blend-file in case you need it: 

https://p7s1-my.sharepoint.com/:f:/g/personal/par0001d_belgium_fhm_de/EvB8XmzbgOtFrT9_slu6fAsBdOKXvf1tWHjhC0nXuLA3xw?e=rUQE9s

**Comment by OmarEmaraDev** [comment]
Thanks for the feedback! I will take a look at those tomorrow.

**Comment by dapa5900** [comment]
@OmarEmaraDev, no worries. 

In that folder there's now also another file where I tried to use this with my book generator setup. I'm not sure if or what I might have done wrong here but in this case I unfortunately can not get it to work. Also, when looking at the imported textures you can see, that page "01" and "09" are both the same image and thus the picture "01" is actually missing. The user slot for page "01" also says 4 instead of 2 like the others.

Maybe you can have a look as well..?

**Comment by OmarEmaraDev** [comment]
@dapa5900 

1. I think this would be the standard way to do things.
2. Fixed in fffea7c7c0e7f7d51967bdc587f321a6f78c9529.
3. Added in c26fe8275dd493f6056864803040291ecb8bf8e5.
4. Fixed in 8f0dd30475f880371ddfd57e3363ae0b554aa9b3.
5. Done in 3c857e27c9bcd48cce3c19d46624b69ffee2e548.
6. Fixed in 7be9bfcaba444d5c57bf9e8108d4760b14b937aa.
7. Fixed in 7be9bfcaba444d5c57bf9e8108d4760b14b937aa.

For the problem in your Blend file, it is partially fixed in 506596beb73660774c70c10cde71b08e7db91662. One problem is still there, however. The add-on doesn't detect when the user makes a new connection to the vector socket, so if you make or remove a connection, make sure to do anything to trigger an update manually. I am thinking of ways to detect that change and act accordingly, but I don't have a clear solution right now, so I will think it over in the next couple of days.

By the way, EEVEE imposes a limit on the number of textures that you can use in a single material, I think it is 16 or 32 depending on your GPU. So you might need to put that in consideration.

**Comment by dapa5900** [comment]
@OmarEmaraDev great, gonna test it tomorrow or latest Friday. Thank you!

**Comment by dapa5900** [comment]
@OmarEmaraDev 

ok, tested it. It works really good now with all the fixes and currently I couldn't find other bugs regarding these. the only thing might be, that the textures still get confused occasionally, especially in cycles (the issue i described above with showing a different picture both in the viewport and image editor; this sometimes then switches to the right one when moving the playhead though so I'm not sure if this might be a Blender Bug...?). It also worked with my book generator now via clearing and re-importing the textures via browse to update. maybe not ideal but at least I can live with this for now, however maybe you will find another way to auto-update...?

the only thing is the amount of textures it can handle. with eevee i can understand that there's a limit (which is 32 in my case) however with cycles it should work for more, right, probably only depending on the RAM of the GPU? unfortunately in my case I wasn't able to make it work while importing more than 41 textures. I tested it on two computers with different GPUSs (one of them has 2 quadro rtx 4000) and also reduced the image resolution of the textures to see if this has an impact. however when going above 41 everything just turns black...

thanks again!

**Comment by OmarEmaraDev** [comment]
@dapa5900 Auto updating is now implemented in f9965c06415b4863f7953c29fae524ac77b78039.

Your first image was an image sequence, not an image, so this might be causing the confusing behavior?

For Cycles, unfortunately, it seems you hit the SVM stack limit. Cycles imposes certain restrictions on the size of the material you can use, this restriction is called the SVM stack limit. I can look into ways to improve this, but maybe later as I don't have much time on my hands now.

**Comment by dapa5900** [comment]
@OmarEmaraDev 

ok, thanks for the info. gotcha, the image sequence was the leftover from my previous setup with the material instances using the frame offset of the image sequence.

I ran into two more things:

1. I was maybe a bit quick with my feedback before as I just realized later that I didn't try the vector input. For me this is still not doing anything at all, when using Texture Coordinates with a mapping node.

2. After updating the add-on with the newest version, I'm able to use the Image Selector with a completely new AN setup in a new blend file with no problems (apart from the stuff I mentioned). However I ran into an issue with my previous files, where I had it setup already. First I just tried the shader as it was before, meaning after the update I already had the Image Selector in the shader graph and was able to update the textures from there. But when I delete the Image Selector node and then try to create a new one, after importing the textures I only get completely blown out textures, both in Eevee and Cycles. You can see here that there's just a hint of the colors the pages have (so there seems to be some color information available) but super bright only.

![blender_Duj6rcZZWe](https://user-images.githubusercontent.com/75205162/125820339-8f1191a8-59a6-4574-bd91-920e28a33d05.png)

**Comment by OmarEmaraDev** [comment]
@dapa5900 Both problems seem to stem from the fact that the vector input is considered as zero.

It seems to be working here. Are you using the same setup?


https://user-images.githubusercontent.com/25300994/125823173-b5a65a46-7ab7-478e-a493-17ea6af0597f.mp4

**Comment by dapa5900** [comment]
@OmarEmaraDev 

yes I do. However I didn't try it on a single object but only on multiple instances generated via AN. Did you try this already?

**Comment by OmarEmaraDev** [comment]
@dapa5900  I tried it on the book generator and it was working fine.

**Comment by dapa5900** [comment]
@OmarEmaraDev 

ok, i tested it again. obviously I also have to re import the textures after adding the vector nodes to make it work.

I just found out that when switching cycles to CPU rendering and using OSL it works with all imported textures (81 in my case now). it's just super slow then.

and, I just ran into this when I tried to clear the list in my setup:

![clearingError](https://user-images.githubusercontent.com/75205162/125917844-532321cc-b4da-4916-9474-3ac0a26fd02c.png)

**Comment by OmarEmaraDev** [comment]
@dapa5900 So just to be clear. Automatic updates don't happen and you still need to manually updated?

**Comment by dapa5900** [comment]
@OmarEmaraDev 

yeah, it seems like.

here's also another thing again with the blown out textures, and connections that get cut. so I replicated the setup in the shader graph like I had it in AN with the instanced materials to be able to use every other texture from the stack for the front and back pages. it worked but now I wanted to again replace the textures and then this happens:

https://user-images.githubusercontent.com/75205162/125931736-cb00c7d2-3b45-4804-b2df-7f994a60b4f6.mp4

Also the question would be, if, when I duplicate the node this way, am I basically wasting available slots and won't be able to use the full 32 textures in eevee for example or doesn't it matter as it's only using every second slot per node? would there be another workaround apart from manually having to import front an back pages separately?

I updated the book generator blend file in the folder i shared with you with the initial version of this demonstration in case you want to replicate this on your side.

**Comment by OmarEmaraDev** [comment]
Slots will be considered even if you don't use them. I think the best way is to do it like this:

![20210716-134120](https://user-images.githubusercontent.com/25300994/125942599-90df3de7-b48a-4799-b62f-fc1fa3d202e7.png)

I attempted a fix in efdb7cee0f54969d88bac6f2b9dad7389dfced99. Can you try the new build? Perhaps recreating the shader from scratch as the add-on don't have versioning code at the moment.

**Comment by dapa5900** [comment]
@OmarEmaraDev 

ok, this setup is working fine for the two sided pages and in general it also works now better however i get a lot of crashes. in the beginning blender was already crashing all the time when i just added the image selector node, then it worked all of a sudden but then it crashes sometimes when trying to import new textures or pluging the color from an emission shader to the bsdf for example... i don't get any errors, is there a way you could look into these, crash reports or something?
the only error i just got now (but also only occasionally, sometimes it works) that after I re-opened the crashed file again and want to clear textures is this:

![error](https://user-images.githubusercontent.com/75205162/125975298-5e49e3d5-779a-41da-ba0d-1f5adb4370ea.png)

quick other question: is there a way to get notification (via mail or so) when there's a new version of AN plus Extra nodes, which I always download here: https://blender.community/c/graphicall/0hbbbc/

**Comment by dapa5900** [comment]
@OmarEmaraDev 

i just got this behavior when exchanging the emission with the bsdf and at the end you can see how blender crashes when unplugging the vector input, which happens to me every time

https://user-images.githubusercontent.com/75205162/125976555-d1e5f2c1-0df4-47de-98c6-ec0ee7690c8d.mp4

**Comment by OmarEmaraDev** [comment]
@dapa5900 When Blender crashes, it usually writes a backtrace somewhere, can you attach that file here? Maybe this [page](https://docs.blender.org/manual/en/latest/troubleshooting/crash.html) will be useful.

It is also often useful to have a terminal open because Blender usually prints something useful there when something happens.

I don't use graphicsall unfortunately, so I am not sure about the notifications.

I still can't replicate the error above, but I will look into rewriting this part to be more reliable.

**Comment by OmarEmaraDev** [comment]
@dapa5900 Error should be fixed in 276eb88208c53ceb94f9235fc5020e0c843cd7f3.

**Comment by dapa5900** [comment]
@OmarEmaraDev 

please find here two crash reports i found in my temp folder:

[bookGenerator_11.crash.txt](https://github.com/OmarEmaraDev/shader-selector-nodes/files/6838449/bookGenerator_11.crash.txt)
[selectorNew.crash.txt](https://github.com/OmarEmaraDev/shader-selector-nodes/files/6838450/selectorNew.crash.txt)

the error with the shader switch seems to be fixed with the latest version. I didn't create the shader from scratch though but it was still working now. thanks for that.

**Comment by dapa5900** [comment]
hi @OmarEmaraDev 

with the latest version of the addon I get a lot of crashes unfortunately. 

Here's the report for a file where Blender crashed immediately when adding the shader:
[selectorNew.crash.txt](https://github.com/OmarEmaraDev/shader-selector-nodes/files/6846370/selectorNew.crash.txt)

And here's a report for a file where I setup the shader already but now Blender crashes already when trying to open this file:
[bookGenerator_11.crash.txt](https://github.com/OmarEmaraDev/shader-selector-nodes/files/6846374/bookGenerator_11.crash.txt)

In the last example I tried to setup multiple materials each pulling in 32 textures and then trying to assign these via AN (so that instances would use another material after 32 instances), so that I can bypass this limitation (don't know if this works then though).

In general I think feature-wise and in terms of usability the addon is in a good state already however at last on my side it's currently very unreliable und results in crashes too often so that I wouldn't want to use it in production yet. Do you think you have the capacity to refine the code and make the addon more stable, please?

**Comment by OmarEmaraDev** [comment]
@dapa5900 Crashes are usually something that is wrong with Blender not add-ons, which is the case here. In this case, most of the crashes you experience are caused by Blender trying to draw the icons in the UI (Maybe caused by the Asset Browser development). I can't replicate the issue in your exact Blender version, so reporting the issue will be difficult.

The one thing I suggest you do now is to try the add-on on the latest Blender nightly build, see if you can replicate the issue there.

**Comment by dapa5900** [comment]
@OmarEmaraDev 

thanks. tried it with the latest 3.0 build from here but it crashed again in both cases described above: https://builder.blender.org/download/daily/

[bookGenerator_shaderSelector.crash.txt](https://github.com/OmarEmaraDev/shader-selector-nodes/files/6855176/bookGenerator_shaderSelector.crash.txt)
[selectorNew.crash.txt](https://github.com/OmarEmaraDev/shader-selector-nodes/files/6855177/selectorNew.crash.txt)

**Comment by OmarEmaraDev** [comment]
@dapa5900 I can finally replicate the crash locally. I will investigate and let you know how it goes.

**Comment by OmarEmaraDev** [comment]
@dapa5900 The crashes should be fixed in b22e24d. Let me know if it is resolved on your end.

**Comment by dapa5900** [comment]
@OmarEmaraDev 

thanks. does the addon have versioning now already or is it recommended the create the shader from scratch again?

**Comment by OmarEmaraDev** [comment]
@dapa5900  It is very unlikely that I will add versioning at this point. Though rebuilding may not be necessary. Try it directly, if it doesn't work, try rebuilding from scratch.

**Comment by dapa5900** [comment]
@OmarEmaraDev 

thanks! I tested it in a fresh scene and it seems to be more stable now. I did get one crash so far when unplugging the vector input but couldn't replicate the crash later on. First I also had the problem that all sockets where disconnecting again when clearing the texture list and adding new textures but also this I couldn't replicate. I would probably need to do more long term testing to see how these things behave in other scenes.

Unfortunately now neither a diffuse nor a principled bsdf work in eevee (they work in cycles) with this addons color input (I only get the purple missing texture color but it used to work in the previous versions). I could only get it to work with an emission shader so far...

**Comment by OmarEmaraDev** [comment]
@dapa5900  My guess is that Diffuse and Principled use their own texture samplers, and since the number of those are limited as mentioned before, the number of image you can use will be lower than if you used an emission shader. Try reducing the number of images and see if the shader works. This probably applies to Cycles as well, more complicated nodes use more of the SVM stack.

Maybe such an add-on wasn't a good idea after all ...

**Comment by dapa5900** [comment]
@OmarEmaraDev 

yeah, reducing it to currently 23 of these textures works (however it used to work with 32 of the same images before). I still think it's a very good tool. I can work with the material instancing approach for now but maybe there will be some improvement regarding these limitations in Cycles and Eevee someday...
